# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ptymini',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/ptymini',
                'lib_path': 'ptymini'},
  'syms': {'ptymini.core': {'ptymini.core.foo': ('core.html#foo', 'ptymini/core.py')}}}
